---
# This role installs httpd

- name: Install apache
  package:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2
   - php
   - php-mysql
   - git

- name: apache service state
  service:
    name: apache2
    enabled: yes
