---
- name: Copy the code from repository
  git: 
    repo: "{{ repository }}" 
    version: "{{ webapp_version }}" 
    dest: "/var/www/html/app"
    force: yes
 
- name: set permissions on applicaton
  file:
    name: /var/www/html/app/aperture.py
    mode: 0755

- name: Install packages 
  apt:
    name: ['python-pip', 'libapache2-mod-wsgi', 'python-mysqldb']
    update_cache: true
    state: present

- name: remove python module if present
  apt:
    name: libapache2-mod-python
    state: absent

- name: Install rpython requirements
  pip:
    requirements: "/var/www/html/app/requirements.txt"

- name: Replace python file
  replace:
    dest: /var/www/html/app/Aperture/__init__.py
    regexp: 'host="redis"'
    replace: host="{{ hostvars['redisdb'].redis.ips[0] }}"

- name: disable default site
  shell: a2dissite 000-default.conf

- name: create site config
  copy:
    src: application.conf
    dest: /etc/apache2/sites-available/application.conf
    force: yes

- name: enable site
  shell: a2ensite application.conf
  notify: restart apache
