---
## This playbook deploys the whole application stack in this site.

- hosts: dbservers
  roles:
  - db
  tags:
  - db

- hosts: webservers
  roles:
  - web
  tags:
  - web

- hosts: lbservers
  roles:
  - haproxy
  tags:
  - lb

- hosts: monitoring
  roles:
  - nagios
  tags:
  - monitoring

- hosts: redis
  roles:
    - redis
  tags:
    - redis
