---
# This role contains common plays that will run on all nodes.

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
 
- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost {{ ansible_hostname }}"
    state: present

- name: install some useful nagios plugins
  package: name={{ item }} state=present
  with_items:
   - nagios-nrpe-plugin
   - nagios-plugins

- name: Install ntp
  package:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp

